"""Import licensed equipment cutouts for in-app use, pinned to RepDB's free tier.
Requires Python 3, Pillow and curl. No runtime network access or AI image processing.
"""
from pathlib import Path
from PIL import Image
import io, json, hashlib, subprocess, concurrent.futures
ROOT=Path(__file__).resolve().parent.parent
REV='9ed9357f09c7566ea0256c57ebd6374ebb8b575e'
BASE=f'https://raw.githubusercontent.com/RepDB/exercise-dataset/{REV}/'
mapping=json.loads((ROOT/'scripts/equipment-images.json').read_text())
out=ROOT/'assets/equipment';out.mkdir(exist_ok=True)
def fetch(path): return subprocess.check_output(['curl','-LfsS','--retry','3',BASE+path])
def download(item):
    equipment, stem=item
    path=f'images/equipment/{stem}.webp'; target=out/(stem+'.png')
    if not target.exists():
        Image.open(io.BytesIO(fetch(path))).convert('RGBA').save(target,'PNG',optimize=True)
    return {'equipment':equipment,'source':BASE+path,'file':str(target.relative_to(ROOT)),'sha256':hashlib.sha256(target.read_bytes()).hexdigest()}
with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool: assets=list(pool.map(download,mapping.items()))
(out/'LICENSE-DATA.md').write_bytes(fetch('LICENSE-DATA.md'))
(out/'manifest.json').write_text(json.dumps({'source':'https://github.com/RepDB/exercise-dataset','revision':REV,'license':'RepDB Free Tier v1.0','attribution':'Exercise data by RepDB (repdb.co)','transformation':'Free equipment WebP converted to lossless transparent PNG; no generative processing.','assets':assets},indent=2)+'\n')
lines=['// Generated by scripts/import-equipment.py. Bundled local assets only.', 'import { Equipment } from "../domain/types";', 'export const equipmentPictures: Partial<Record<Equipment, number>> = {']
for id,stem in mapping.items(): lines.append(f'  {json.dumps(id)}: require("../../assets/equipment/{stem}.png"),')
lines.append('};')
(ROOT/'src/data/equipmentPictures.ts').write_text('\n'.join(lines)+'\n')
print(f'Bundled {len(assets)} equipment pictures.')
